### ISSUE TITLE
Provide direct rule documentation links

### ISSUE THREAD

**Issue by apexskier** [standard/eslint-plugin-standard#14]
It would be helpful for various plugins in the eslint community to provide direct links to each rule's documentation. This would allow better integration with [eslint-rule-documentation](https://github.com/jfmengels/eslint-rule-documentation/) (requested [in this PR](https://github.com/jfmengels/eslint-rule-documentation/pull/2#issuecomment-239359673)) which will soon be used by [Atom's eslint integration package](https://github.com/AtomLinter/linter-eslint/pull/653#issuecomment-239225284).

A few ways this could be done:
- Create a `rule.md` file along side each rule's source. (e.g. `https://github.com/xjamundx/eslint-plugin-standard/blob/master/rules/array-bracket-even-spacing.md`) Link to each rule from a "rules" section in the main README.
- Follow the [pattern described by eslint-rule-documentation](https://github.com/jfmengels/eslint-rule-documentation/blob/master/contributing.md): `https://github.com/xjamundx/eslint-plugin-standard/blob/master/docs/rules/RULENAME.md` by creating a `docs/rules` dir. (I actually don't favor this one, since I think it would make doc drift easier)
- Add headings to your main README so each rule can be directly linked to.
  
  ``` md
  ### Rules Explanations
  ...
  #### object-curly-even-spacing
  Like...
  ```

Since this plugin doesn't have a large number of rules, I don't think this is a big deal, but if you're open to it I can get a quick PR out.

**Comment by jfmengels** [comment]
I agree that having one file per rule would be better, as it would allow for more complete documentation of your rules (reasoning, how it works, examples, when to use it...).

> Follow the pattern described by eslint-rule-documentation: https://github.com/xjamundx/eslint-plugin-standard/blob/master/docs/rules/RULENAME.md

That is the "usual" documentation pattern (used by most of these [plugins](https://github.com/jfmengels/eslint-rule-documentation/blob/master/plugins.json)), by the core ESLint rules in the ESLint repo, and advocated by ESLint, as it is the one used by [generator-eslint](https://github.com/eslint/generator-eslint) when creating new rules.

**Comment by voxpelli** [comment]
Is this still needed now that #24 has been merged or do they deal with two different things in regards to documentation of rules?

**Comment by feross** [comment]
I think we can consider this completed. If someone also wants to send a PR that does one file per rule (as per the ESLint norm), that's more than welcome!
