### ISSUE TITLE
Transfer to "standard" organization

### ISSUE THREAD

**Issue by feross** [standard/eslint-plugin-standard#22]
Hey @xjamundx, what do you think of transferring this repo to the @standard organization?

Context: https://github.com/standard/standard/issues/846

**Comment by xjamundx** [comment]
Great idea!

**Comment by xjamundx** [comment]
@feross I'd love to gift this to the standard org. Anything I need to do to make that happen?

**Comment by xjamundx** [comment]
@feross ^^ let's do this

**Comment by feross** [comment]
@xjamundx Cool, let's do it. Since you're a member of the @standard org already, you should be able to transfer it in.

Guide here: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by feross** [comment]
@xjamundx Ping!

**Comment by voxpelli** [comment]
This seems completed now? I added #28 as a follow up to this issue

**Comment by feross** [comment]
Yep, this is complete.
