### ISSUE TITLE
`standard/array-bracket-even-spacing` breaks in destructuring with flowtype

### ISSUE THREAD

**Issue by qm3ster** [standard/eslint-plugin-standard#23]
`([x, y]: C) => x + y` gives `Expected consistent spacing (standard/array-bracket-even-spacing)`
`([x, y]) => x + y` and `(c: C) => x + y` are fine.
Should I file the issue here or at [gajus/eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype/issues)?
`--fix` doesn't get it there, but it is actually satisfied with the weird `([ x, y]: C) => x + y`

**Comment by xjamundx** [comment]
Sorry I slept on this for so long. Let me try to follow up!

**Comment by CherryDT** [comment]
I noticed another weird behavior with this.

This works:

```javascript
const x = y(([, a, b, c, d]) => ({ /* ... */ }))
```

...as does this:

```javascript
const x = y(([, a, b, /* c is unused */, d]) => ({ /* ... */ }))
```

But this gives me an error `Expected consistent spacing (standard/array-bracket-even-spacing)`:

```javascript
const x = y(([/* always zero */, a, b, c, d]) => ({ /* ... */ }))
```

**Comment by feross** [comment]
This package isn't used by standard anymore, as of standard v16. See: standard/standard/issues/1316
