### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by strugee** [standard/eslint-plugin-standard#37]
**What version of this package are you using?**

I'm looking at current git master (so, 4.0.1 / ddbab93333417d568716415c771601ee4a39fa2a; take your pick)

**What problem do you want to solve?**

It's hard to see what changed between versions (this problem is especially acute for semver-major version changes).

**What do you think is the correct solution to this problem?**

This project could use a change log.

See http://keepachangelog.com

**Are you willing to submit a pull request to implement this change?**

I would love to but realistically I don't have time and don't want to promise something I know I likely won't follow through on :(

Thank you for maintaining this project though <3 even if you don't ever actually start a changelog... I know it's boring and we all have things to do

**Comment by feross** [comment]
@strugee I appreciate your suggestion but I just don't have time to maintain a changelog for this particular project.
