### ISSUE TITLE
Deprecate current version or release and deprecate new major version

### ISSUE THREAD

**Issue by voxpelli** [standard/eslint-plugin-standard#38]
It's easy to miss that `eslint-config-standard` doesn't require this module anymore (https://github.com/standard/standard/issues/1316)

I can see why deprecating the current major isn't desirable as it isn't really deprecated for those on the `standard` versions that uses it.

But for those who are upgrading it would be good to get a hint that the entire module, and releasing a `5.x` module that is functionally identical to `4.x`, which one then deprecates, could probably help with that?

**Comment by feross** [comment]
I agree. Just released 5.0.0 and deprecated it!
