### ISSUE TITLE
Why bump to version 5.0? Can't ask a question as discord link is broken

### ISSUE THREAD

**Issue by gruckionvit** [standard/eslint-plugin-standard#39]
**What version of this package are you using?**

`4.1.0` 

**What operating system, Node.js, and npm version?**

N/A

**What happened?**

Releases not tag properly so hard to know what's changed

https://github.com/standard/eslint-plugin-standard/commit/620b262dc21124e743fcdbe4f669e14e59978f53

This commit just shows the version bump nothing else. What gives?

**What did you expect to happen?**

To know why a major version bump has occured and what breaking changes this will have on my project.

**Are you willing to submit a pull request to fix this bug?**

No

**Comment by voxpelli** [comment]
It was created as a way to deprecate the module without causing noise for those who were on the older version / using an older version of standard.

See: https://github.com/standard/eslint-plugin-standard/issues/38
